### ISSUE TITLE
error: the following arguments are required: video_filename

### ISSUE THREAD

**Issue by Keesboersma** [PowercoderJr/lords-gifts-counter#2]
hello,

Where do I enter the path for the video? I get this message every time: error: the following arguments are required: video_filename.

**Comment by PowercoderJr** [comment]
Hi, pass it as parameter to command line after script name. For example: `python analyze.py myvideo.mp4`

**Comment by Keesboersma** [comment]
Thanx that part works. 
now i get the following: PS C:\Python\lords-gifts-counter-master> python analyze.py video1.MP4
Read video 1280x720 Error: unsupported resolution Currently supported resolutions: 2340x1080

**Comment by PowercoderJr** [comment]
Sorry, as it said, only one resolution supported. It is needed to create markup manually for each screen.

**Comment by Keesboersma** [comment]
I modified the video and now it works. but now i have the following: 
Data loaded successfully Traceback (most recent call last):
  File "C:\Python\lords-gifts-counter-master\analyze.py", line 201, in <module>main(args)
  File "C:\Python\lords-gifts-counter-master\analyze.py", line 162, in main
    cv2.imshow('sender_fragment', sender_fragment)
                                  ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'sender_fragment' where it is not associated with a value
PS C:\Python\lords-gifts-counter-master>

Sorry for all these questions

**Comment by PowercoderJr** [comment]
It can be the same thing as here: https://github.com/PowercoderJr/lords-gifts-counter/issues/1#issuecomment-864301199 or maybe because of video resize. It's not enough to just match the shape, UI elements must match the original patterns.

**Comment by Keesboersma** [comment]
Yeah same problem. how do you make the recording?

**Comment by Keesboersma** [comment]
Doesnt work with option 1 and 2 but does with version 0 But no data in the excel file

**Comment by PowercoderJr** [comment]
Starting from very top of list

**Comment by Keesboersma** [comment]
I actually mean how to make a video with a resolution of: 2340x1080

**Comment by HalfDemon2** [comment]
You can go on a website and do it, or you can use da Vinci resolve to upscale the resolution
